services:
  minio1:
    image: quay.io/minio/minio:${MINIO_RELEASE}
    container_name: minio1
    hostname: minio1
    restart: unless-stopped
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    expose:
      - '9000'
      - '9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - minio-network
    volumes:
      - data1-1:/data1
      - data1-2:/data2
      - misc1:/data

volumes:
  data1-1:
  data1-2:
  misc1:

networks:
  minio-network:
    name: minio-network
    external: true
