services:
  minio4:
    image: quay.io/minio/minio:${MINIO_RELEASE}
    container_name: minio4
    hostname: minio4
    restart: unless-stopped
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    expose:
      - '9000'
      - '9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - minio-network
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  minio_nginx_stable:
    image: nginx:stable
    container_name: minio_nginx_stable
    hostname: minio_nginx_stable
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - TZ=Asia/Kuala_Lumpur
    networks:
      - minio-network
    depends_on:
      - minio4

volumes:
  data4-1:
  data4-2:

networks:
  minio-network:
    name: minio-network
    external: true
