services:
  minio2:
    image: quay.io/minio/minio:${MINIO_RELEASE}
    container_name: minio2
    hostname: minio2
    restart: unless-stopped
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    expose:
      - '9000'
      - '9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - minio-network
    volumes:
      - data2-1:/data1
      - data2-2:/data2

volumes:
  data2-1:
  data2-2:

networks:
  minio-network:
    name: minio-network
    external: true
